from typing import Protocol

from app.domain.entities import CartItem, Coupon, Order, Product, Review, User


class UserRepository(Protocol):
    def get(self, user_id: int) -> User | None: ...
    def get_by_email(self, email: str) -> User | None: ...
    def create(self, user: User) -> User: ...
    def next_id(self) -> int: ...


class ProductRepository(Protocol):
    def list(self) -> list[Product]: ...
    def get(self, product_id: int) -> Product | None: ...
    def create(self, product: Product) -> Product: ...
    def update(self, product: Product) -> Product: ...
    def delete(self, product_id: int) -> None: ...
    def next_id(self) -> int: ...


class CartRepository(Protocol):
    def list_items(self) -> list[CartItem]: ...
    def get_item(self, product_id: int) -> CartItem | None: ...
    def set_item(self, item: CartItem) -> CartItem: ...
    def delete_item(self, product_id: int) -> None: ...
    def clear(self) -> None: ...
    def set_coupon(self, code: str | None) -> None: ...
    def get_coupon(self) -> str | None: ...
    def set_shipping_method(self, shipping_method: str) -> None: ...
    def get_shipping_method(self) -> str: ...


class OrderRepository(Protocol):
    def list(self) -> list[Order]: ...
    def get(self, order_id: int) -> Order | None: ...
    def create(self, order: Order) -> Order: ...
    def update(self, order: Order) -> Order: ...
    def next_id(self) -> int: ...


class CouponRepository(Protocol):
    def list(self) -> list[Coupon]: ...
    def get(self, code: str) -> Coupon | None: ...


class ReviewRepository(Protocol):
    def list_for_product(self, product_id: int) -> list[Review]: ...
    def create(self, review: Review) -> Review: ...
    def next_id(self) -> int: ...
